# version: 2

# updates:
#   - package-ecosystem: cargo
#     directory: "webserver/"
#     schedule:
#       interval: monthly
#     open-pull-requests-limit: 5

#   - package-ecosystem: pip
#     directory: "xythrion/"
#     schedule:
#       interval: monthly
#     open-pull-requests-limit: 5
