version: 2

updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: daily
      time: "07:00"
    open-pull-requests-limit: 5

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "07:00"
    open-pull-requests-limit: 5
