version: "3.8"

services:

  postgres:
    image: postgres:latest
    init: true
    restart: always

    env_file:
      - .env

    expose:
      - 5432

    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  xythrion:
    container_name: xythrion
    init: true
    restart: always

    depends_on:
      - postgres

    env_file:
      - .env

    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./logs:/xythrion/logs:rw
      - .:/xythrion:ro

    ports:
      - "5005:5000"
