version: "3.9"

services:

  xythrion:
    restart: always

    depends_on:
      - webserver

    build:
      context: xythrion
      dockerfile: Dockerfile

    volumes:
      - ./logs:/xythrion/logs:rw
      - .:/xythrion:ro

  webserver:
    restart: always

    build:
      context: webserver
      dockerfile: Dockerfile
