version: "3.8"

services:

  xythrion:
    container_name: xythrion
    init: true
    restart: always

    env_file:
      - .env

    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./logs:/xythrion/logs:rw
      - .:/xythrion:ro
