name: Greetings

on:
  pull_request:
    branches: [ main ]
  issues:
    branches: [ main ]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for the issue! This issue will be addressed in a reasonable amount of time.'
        pr-message: 'Thank you for the pull request! This contribution will be addressed in a reasonable amount of time.'
